# NumPy Arrays

A NumPy array is like a specialized, super-efficient container designed only for numbers (or other single data types). Because it's so specialized, it can do mathematical operations on all its numbers much, much faster than a regular Python list.

## Key Features of NumPy Arrays 

- **Fast Operations:** They are optimized to perform mathematical operations on entire collections of numbers at once.
- **Memory Efficient:** They use less memory than Python lists for the same amount of numerical data.
- **Homogeneous:** All elements in a NumPy array must be of the same data type (e.g., all integers, all decimal numbers, etc.). This strictness is what allows them to be so fast and efficient.
- **Multi-dimensional:** While Python lists are mostly 1-dimensional (a single row of items), NumPy arrays can easily be 2D (like a table/matrix), 3D (like a cube of numbers), or even more dimensions! This is crucial for things like images (2D or 3D) and complex AI models.

## Get started with NumPy

In [1]:
import numpy as np # This line is almost always at the top of a Python file using NumPy

### 1-Dimnetional Array

In [2]:
my_1d_list = [10,20,30,40,50]
numpy_array = np.array(my_1d_list)

In [4]:
print("My 1D NumPy Array:", numpy_array)
print("Type of my_numpy_array_1d:", type(numpy_array))
print("Shape of my_numpy_array_1d:", numpy_array.shape) # (5,) means 5 elements in 1 dimension
print("-" * 30)

My 1D NumPy Array: [10 20 30 40 50]
Type of my_numpy_array_1d: <class 'numpy.ndarray'>
Shape of my_numpy_array_1d: (5,)
------------------------------


### 2-Dimensional Array

In [5]:
two_dimentional_array = [[1,2,3],[4,5,6],[7,8,9]]
numpy_array = np.array(two_dimentional_array)

In [7]:
print("My 2D NumPy Array:\n", numpy_array) # \n means start a new line for better display
print("Shape of my_numpy_array_2d:", numpy_array.shape) # (3, 3) means 3 rows, 3 columns
print("-" * 30)

My 2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of my_numpy_array_2d: (3, 3)
------------------------------


### Zero Array(Array Containing only ZERO)

In [11]:
zero_array = np.zeros(5) # 5 zeros
zero_array

array([0., 0., 0., 0., 0.])

### Ones Array(Array Containing only One)

In [17]:
one_array = np.ones((2,3)) # a 2x3 array of ones
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

### Range of numbers Array(Array Containing Range of numbers)

In [19]:
range_array = np.arange(0, 10, 2) # numbers from 0 up to (but not including) 10, stepping by 2
range_array

array([0, 2, 4, 6, 8])

---
## Indexing NumPy Arrays
Indexing in NumPy is very similar to Python lists, but it gets more powerful with multi-dimensional arrays. Remember: indexing always starts from 0!

### a. 1-Dimensional Array Indexing

In [20]:
scores = np.array([100, 95, 80, 70, 10])

print("First score (index 0):", scores[0])   # Output: 100
print("Third score (index 2):", scores[2])   # Output: 80
print("Last score (negative index):", scores[-1]) # Output: 10 (Accesses from the end)

First score (index 0): 100
Third score (index 2): 80
Last score (negative index): 10


### b. 2-Dimensional Array Indexing (Rows and Columns)

In [21]:
data = np.array([[10, 11, 12],
                 [20, 21, 22],
                 [30, 31, 32]])

print("Our 2D data array:\n", data)
print("-" * 30)

# Get the element at row 0, column 1 (which is 11)
print("Element at [0, 1]:", data[0, 1]) # Output: 11

# Get the element at row 1, column 2 (which is 22)
print("Element at [1, 2]:", data[1, 2]) # Output: 22

# Get an entire row (e.g., row 0)
print("Entire row 0:", data[0, :]) # Output: [10 11 12]
                                 # The `:` means "all columns" in this row

# Get an entire column (e.g., column 1)
print("Entire column 1:", data[:, 1]) # Output: [11 21 31]
                                 # The `:` means "all rows" in this column

Our 2D data array:
 [[10 11 12]
 [20 21 22]
 [30 31 32]]
------------------------------
Element at [0, 1]: 11
Element at [1, 2]: 22
Entire row 0: [10 11 12]
Entire column 1: [11 21 31]


---
## Slicing Arrays
Slicing is like taking a continuous portion of your array. It uses the start:stop:step notation, just like Python lists.

### Slicing 1D Array

In [23]:
numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original numbers:", numbers)

Original numbers: [0 1 2 3 4 5 6 7 8 9]


In [24]:
# Get elements from index 2 up to (but not including) index 6
print("Slice [2:6]:", numbers[2:6]) # Output: [2 3 4 5]

Slice [2:6]: [2 3 4 5]


In [25]:
# Get elements from the beginning up to index 5
print("Slice [:5]:", numbers[:5])   # Output: [0 1 2 3 4]

Slice [:5]: [0 1 2 3 4]


In [26]:
# Get elements from index 7 to the end
print("Slice [7:]:", numbers[7:])   # Output: [7 8 9]

Slice [7:]: [7 8 9]


In [27]:
# Get every other element (step of 2)
print("Slice [::2]:", numbers[::2]) # Output: [0 2 4 6 8]

Slice [::2]: [0 2 4 6 8]


### Slicing 2D Array

In [28]:
# Slicing in 2D arrays:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("\nOriginal Matrix:\n", matrix)


Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# Get the first two rows, and columns 1 through 3 (not including 3)
sub_matrix = matrix[0:2, 1:3]
print("Sub-matrix [0:2, 1:3]:\n", sub_matrix)

Sub-matrix [0:2, 1:3]:
 [[2 3]
 [6 7]]


---
## Basic Operations on NumPy Arrays

### 1. Element-wise Operations
add, subtract, multiply, or divide entire arrays by a number, or even by another array (if they have the same shape). This applies the operation to each individual element.

In [32]:
array1 = np.array([1, 2, 3])
array2 = np.array([10, 20, 30])

In [34]:
# add a number to every element
print("Array1 + 5:", array1 + 5)

Array1 + 5: [6 7 8]


In [35]:
# Multiply every element by a number
print("Array1 * 2 =>", array1 * 2)

Array1 * 2 => [2 4 6]


In [36]:
# Add two arrays (element by element)
print("Array1 + Array2:", array1 + array2) # Output: [11 22 33]

Array1 + Array2: [11 22 33]


In [37]:
# Multiply two arrays (element by element)
print("Array1 * Array2:", array1 * array2) # Output: [10 40 90]

Array1 * Array2: [10 40 90]


### 2. Aggregate Operations
NumPy provides many functions to calculate things like sum, mean (average), min, max of all elements in an array.

In [38]:
data_values = np.array([10, 5, 20, 15, 30])
data_values

array([10,  5, 20, 15, 30])

#### Sum OF all values

In [39]:
np.sum(data_values)

np.int64(80)

#### Average (Mean) of values

In [40]:
np.mean(data_values)

np.float64(16.0)

#### Maximum value

In [41]:
np.max(data_values)

np.int64(30)

#### Minimum value

In [42]:
np.min(data_values)

np.int64(5)

### 3. Operations along Axes (for Multi-dimensional Arrays)
When you have 2D or higher-dimensional arrays, you can perform operations along specific axes.

- axis=0: Operations are done column-wise (down the columns).
- axis=1: Operations are done row-wise (across the rows).

In [44]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original Matrix:\n", matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]]


#### Sum of elements in each column (axis=0)

In [45]:
np.sum(matrix, axis=0)

array([5, 7, 9])

#### Sum of elements in each row (axis=1)

In [46]:
np.sum(matrix, axis=1)

array([ 6, 15])

#### Same for mean, max, etc.

In [47]:
print("Mean along axis 0:", np.mean(matrix, axis=0))
print("Mean along axis 1:", np.mean(matrix, axis=1))

Mean along axis 0: [2.5 3.5 4.5]
Mean along axis 1: [2. 5.]


---
---
# Mini Project (30 mins): 
Create a NumPy array, compute mean, and multiply two 2x2 matrices.

In [53]:
array1 = np.array([
    [1,2,3],
    [4,5,6]
])
array2 = np.array([
    [7,8,9],
    [10,11,12]
])
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [54]:
# Compute mean
print(np.mean(array1))
print(np.mean(array2))

3.5
9.5


In [56]:
# Multiply two 2x2 matrices
array1 * array2

array([[ 7, 16, 27],
       [40, 55, 72]])